export const REQUEST_API = 'REQUEST_API';

export const RESET_ERROR = 'RESET_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const GETCURRENTUSER_REQUEST = "GETCURRENTUSER_REQUEST";
export const GETCURRENTUSER_SUCCESS = "GETCURRENTUSER_SUCCESS";
export const GETCURRENTUSER_FAILURE = "GETCURRENTUSER_FAILURE";
