exports.run = async (queue) => {
  console.log("create match start");
  const MatchObject = Parse.Object.extend("match");
  const newMatch = new MatchObject();
  newMatch.set("status", "pending");
  newMatch.set("size", queue.get("size")[0]);
  newMatch.set("position", [queue.get("position")[0]]);
  newMatch.set("language", queue.get("language")[0]);
  newMatch.set("region", queue.get("region")[0]);
  newMatch.set("type", queue.get("type")[0]);
  newMatch.set("skill", queue.get("skill"));
  const savedMatch = await newMatch.save();
  console.log("create match saved");
  savedMatch.relation("players").add(queue);
  const updatedMatch = await savedMatch.save();
  console.log("create match player added");
  queue.set("match", updatedMatch);
  queue.set("status", "found");
  await queue.save();
  console.log("create match player updated");
};